name: Github Pages Blog

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          # extended: true

      - name: git clone
        run:  git clone git@github.com:janineyylu/janineyylu.github.io.git ${GITHUB_WORKSPACE}/checkout

      - name: Build
        run: hugo -D 

      - name : Deploy 
        run: $GITHUB_WORKSPACE/.github/workflows/deploy.sh
